// todo
export const ADD_TODO = 'ADD_TODO';
export const TOGGLE_COMPLETE_TODO = 'TOGGLE_COMPLETE_TODO';
export const REMOVE_TODO = 'REMOVE_TODO';
export const EDIT_TODO = 'EDIT_TODO';
export const TOGGLE_EDIT_TODO = 'TOGGLE_EDIT_TODO';
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER';

export const VisibilityFilters = {
  SHOW_ALL: 'SHOW_ALL',
  SHOW_COMPLETED: 'SHOW_COMPLETED',
  SHOW_ACTIVE: 'SHOW_ACTIVE'
};


// hover
export const SET_HOVER_STATE = 'SET_HOVER_STATE'
export const SET_HOVER_COLOR = 'SET_HOVER_COLOR'


// reddit
export const REQUEST_POSTS = 'REQUEST_POSTS'
export const RECEIVE_POSTS = 'RECEIVE_POSTS'
export const SELECT_REDDIT = 'SELECT_REDDIT'
export const INVALIDATE_REDDIT = 'INVALIDATE_REDDIT'

// expenses
export const  RETRIEVE_EXPENSES = 'RETRIEVE_EXPENSES'
export const  ADD_EXPENSE = 'ADD_EXPENSE'
export const  EDIT_EXPENSE = 'EDIT_EXPENSE'
export const  REMOVE_EXPENSE = 'REMOVE_EXPENSE'
export const  IS_SAVING_EXPENSE = 'IS_SAVING_EXPENSE'
